### ISSUE TITLE
Fitness trend will not preview tomorrow (but works fine from the day after tomorrow onwards)

### ISSUE THREAD

**Issue by fredcostapinto** [thomaschampagne/stravistix#611]
I posted before about my fitness trend not showing today (https://github.com/thomaschampagne/stravistix/issues/558) and it was solved. 
Nonetheless, now it does not let me preview tomorrow (but shows everything up to today and also from the day after tomorrow onwards).

Plugin 6.2.1 stable
Chrome  66.0.3359.181 64 bits
Windows 10 pro 64-bit

![image](https://user-images.githubusercontent.com/37844529/41113270-85eb85e4-6a57-11e8-8a51-c36f58b9c2d7.png)

![image](https://user-images.githubusercontent.com/37844529/41113323-b3134192-6a57-11e8-9c43-a3d0bb556c4c.png)

**Comment by thomaschampagne** [comment]
Can you provide me an export of your history? What is your timezone? City?

**Comment by fredcostapinto** [comment]
Hey @thomaschampagne sure I can. I'm on a different machine now but the same issue happens here as well (MacOS 10.13.4, Chrome 67.0.3396.79 (Official Build) (64-bit), Plugin 6.2.1 Stable).

City is Sao Paulo, Brazil. Timezone is GMT-3. History is attached. Thanks!


[2018.6.8-7.38_v6.2.1.history.json.zip](https://github.com/thomaschampagne/stravistix/files/2084037/2018.6.8-7.38_v6.2.1.history.json.zip)

**Comment by fredcostapinto** [comment]
@thomaschampagne I don't know if you had the chance to tackle this issue yet but definitely looks related to my time zone (as you suspected).
Just by changing from GMT-3 to GMT-0 (Sao Paulo to London) the issue is gone.
Best,
Fred

![image](https://user-images.githubusercontent.com/37844529/41529557-f5239900-72c3-11e8-90e1-0a72748a8609.png)

**Comment by thomaschampagne** [comment]
@fredcostapinto I tested your export at home and i were not able to see the problem with Sao  Paulo timezone :(

But it should be fixed by https://github.com/thomaschampagne/stravistix/issues/558 on April 20 right? (You were the author of this previous ticket)

Can you give me more details i don't see :) ?

**Comment by fredcostapinto** [comment]
Hey @thomaschampagne I've been following the updates on the app and it looks even more amazing with each patch, as always. Nonetheless, I noticed this issue still persists (at least on my timezone). I can preview the day after tomorrow and onwards on the fitness trend, but tomorrow doesn't exist on the chart.
Have you had the chance to take a closer look on this? Thanks as always. The most important add-on to strava to date in my opinion (which I have recommended to all my friends btw).
Best!

**Comment by thomaschampagne** [comment]
@fredcostapinto Could to validate/test the fix using the CI build upcoming in few minutes at : https://bitbucket.org/thomaschampagne/stravistix-ci-builds/downloads/ 

Thanks !

**Comment by fredcostapinto** [comment]
Perfect! Thanks a lot @thomaschampagne I just confirmed and it finally works with this build.
Best!

**Comment by thomaschampagne** [comment]
Oura!!  Live in next update ;)
